name: Compile the module

on: [push]

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[build]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Pull changes
      run: |
        git pull origin master
    - name: Build the code
      run: |
        python builder.py
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Auto Builder"
        git add -f *
        git commit -m "Generate build"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
